platform :ios, '9.0'
use_frameworks!

target 'DHNative' do
source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' 
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/goinstant/pods-specs-public'

#salesforce pods
pod 'SalesforceSDKCore'
pod 'SalesforceNetwork'
pod 'SalesforceRestAPI'
pod 'JB4ASDK'
pod 'SOS', '1.3.0'


#3rd party pods
pod 'ENSwiftSideMenu', '~> 0.1.1'
pod "GoogleMaterialIconFont"
pod "DGElasticPullToRefresh"
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
pod 'SwiftyJSON'
pod 'SDWebImage', '~>3.8'

end
